### ISSUE TITLE
Better event filtering

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-socketio#2]
Currently event filtering is only possible by implementing `created`, `updated` etc. methods on the service. This does not support custom service events (see https://github.com/feathersjs/feathers/issues/133 and https://github.com/feathersjs/feathers/issues/111) or filter chains. A better way would be to add a `filter` mixin method to services like this:

```js
app.service('todos').filter('created', function(todo, params, callback) {});
```

**Comment by marshallswain** [comment]
This doesn't take care of the custom events issue, but is it currently possible to provide an array of event filters the same way it's done for hooks?  If not, that would be a really great thing to include, imo.  Then we can have a filter library the same way that we will for hooks.

**Comment by daffl** [comment]
Not at the moment but https://github.com/feathersjs/feathers-commons/pull/15 will add all of that. As you suggested, event filtering works pretty much the same as hooks, except that you will - additionally to the hook object - also get the current dispatch data and the connection (`params` in the old hooks). So you can do things like:

```
const todos = app.service('todos');

// Blanket filter out all connections that don't belong to the same company
todos.filter(function(data, connection) {
  if(data.company_id !== connection.user.company_id) {
    return false;
  }

  return data;
});

// After that, filter todos, if the user that created it and the connected user aren't friends
todos.filter('created', function(data, connection, hook) {
  const todoUserId = hook.params.user._id;
  const currentUserFriends = connection.user.friends;
  
  if(currentUserFriends.indexOf(todoUserId) === -1) {
    return false;
  }

  return data;
});

// Other ways to use it
todos.filter({
  removed: [a, b],
  updated: function(data, connection, hook, callback) {}
});
```

All of that will be backwards compatible with the legacy `created`, `updated` etc. methods.
Would you mind pasting the above snippet into the docs so that we don't forget about?

**Comment by marshallswain** [comment]
Yep. I added it to the events page.

**Comment by ekryski** [comment]
Now that this landed in `feathers-commons` it should be good to close.

**Comment by daffl** [comment]
I still have to make a `feathers-socket-commons` and `feathers-socketio` and `feathers-primus` release. Just wrapping up a couple of tests but should be prety quick.

**Comment by green-coder** [comment]
At https://docs.feathersjs.com/api/events.html#event-filtering it is written :

> Filter functions run for every connected client on every event and should be optimized for speed and chained by granularity.

I am wondering if for some cases, instead of running a filter for each connection, that would not be more efficient to reverse the relation and just group the connections by criteria (e.g. by room), run no filters and sent the grouped connections the event?

Would this way of filtering be allowed by / pluggable into the current implementation of `feathersjs-socketio`?

**Comment by green-coder** [comment]
Nevermind, I found the related issue.
https://github.com/feathersjs/feathers/issues/388#issuecomment-310963061
