### ISSUE TITLE
README.md broken link to provider documentation

### ISSUE THREAD

**Issue by ElliotPsyIT** [feathersjs/feathers-socketio#23]
I just noticed the link to provider API doc within the README.md is broken.

`Note: For the full API documentation go to ` http://feathersjs.com/docs/providers.html

I'd submit a PR (as a newbie, it would be my 2nd ever :)), but not sure which doc page you'd like referenced.  Could link to feathers doc opening page http://docs.feathersjs.com/ or to the feathers-socketio page http://docs.feathersjs.com/real-time/socket-io.html or other.

**Comment by daffl** [comment]
I'd change it to the http://docs.feathersjs.com/real-time/socket-io.html page. Looking forward to your PR!
