### ISSUE TITLE
"Can't find variable: Reflect" on bad requests/authentication token missing; react-native

### ISSUE THREAD

**Issue by imalbert** [feathersjs/feathers-socketio#31]
Hi, I have this problem wherein whenever I receive bad requests/authentication token missing error responses from a service I get a "Can't find variable: Reflect" red screen error.

![screenshot 2016-06-15 15 09 12](https://cloud.githubusercontent.com/assets/12537973/16070944/37ba2dc4-330b-11e6-9c20-bb301674693d.png)

My react-native version is 0.24

I created a repro using feathers-chat that creates a auth-token-missing error @ https://github.com/imalbert/react-native-socketio-error

**Comment by imalbert** [comment]
I forgot to say, this happens when the chrome debugger is turned off; also in the bundled versions for ios and android

**Comment by daffl** [comment]
Try installing `babel-polyfill` and then in your main application file adding

```js
if(!global._babelPolyfill) { require('babel-polyfill'); }
```

**Comment by imalbert** [comment]
This fixed the problem, thanks a lot! I did not have to install `babel-polyfill` because it seems to be already included in `react-native init`
