### ISSUE TITLE
Disable/restrict failed request queue?

### ISSUE THREAD

**Issue by ryuken** [feathersjs/feathers-socketio#38]
Hi I'm searching for a way to disable or restrict the failed request queue to 1.
So basically socket.io queue's failed requests when network connection is gone and resends those when connection resumes.

How can I stop this behaviour or restrict the maximum amount of requests?

**Comment by daffl** [comment]
I found [this SO answer](http://stackoverflow.com/questions/11632969/how-configure-reconnecting-in-socket-io) to set the Socket.io max reconnection retries. Not sure if that is what you are looking for. You might have more luck finding an answer in the Socket.io channels or GitHub.

**Comment by ryuken** [comment]
Nah that's the reconnection timings.
If the connection is lost and you still try to do stuff, the client will queue those requests and send them when reconnected.

I solved it by checking if there is any internet connection in all actions lol, but its a kinda crappy solution. I wish there was a way to stop this behaviour of socket.io

**Comment by ekryski** [comment]
@ryuken care to post the solution for reference? 😁

**Comment by ryuken** [comment]
I didn't solve it with socketio (they don't support this).
I checked if there is any internet connection before dispatching my events lol.
