### ISSUE TITLE
Upgrade to socket.io 1.4

### ISSUE THREAD

**Issue by timelesshaze** [feathersjs/feathers-socketio#39]
There seem to be no breaking changes (npm test is passing).
Operations returning large results would benefit from the automatic compression.

**Comment by daffl** [comment]
The `^1.3.7` version range matches version `1.4.x` as well. If you reinstall your projects with a clean cache and run `npm ls socketio` you will see that you get the latest 1.4.

We use [Greenkeeper](https://greenkeeper.io/) for all our repositories to keep dependencies up to date and it will automatically submit a pull request if a new version that does not match the range or where the build fails got published.

**Comment by timelesshaze** [comment]
Thank you!
