### ISSUE TITLE
Get data after connection established

### ISSUE THREAD

**Issue by rrubio** [feathersjs/feathers-socketio#59]
Hi Guys,

This might be a super dumb question, but here it goes. 

As per example provided under this repository, my client is able to connect fine and i do get a response from "socket.emit('news', { hello: 'world' });".

How do i go about CRUD, fetching data from the example provided? is there an example somewhere? I haven't been able to use feathers-client on my app due to some errors under "ionic", i'm using vanilla socket.io syntax (see below)

`this.messages = [];
        this.socketHost = "http://localhost:3030";
        this.zone = new NgZone({enableLongStackTrace: false});
       
        this.chatBox = "";
        this.socket.socketService.subscribe(event => {
        console.log('message received from server... ', event);
        if (event.category === 'messages'){
          this.zone.run(() => {
            this.messages.push(event.message);
            this.chat.scrollTo(0, 99999, 0);
          });
        }
      }); //end of subscribe`

**Comment by daffl** [comment]
What was the error you were getting? We do recommend using the client if possible and Feathers client should work in most JavaScript environments.

Either way, you can find documentation for direct socket.io communication at https://docs.feathersjs.com/clients/vanilla-socket-io.html.

**Comment by rrubio** [comment]
Thank you @daffl, 

I didn't keep the exact message, but it was something along the lines of an emit error due to no export under the feathers-client library. This is on ionic framework "ionic2".

**Comment by daffl** [comment]
Did you load `feathers-client/dist/feathers` or just `feathers-client`?

**Comment by rrubio** [comment]
feathers-client only, should i try with "dist"?

**Comment by daffl** [comment]
`feathers-client` itself will only work with a module loader that works with npm. Anything else will should use the pre-built UMD wrapped distributable.

**Comment by rrubio** [comment]
Cool! thank you. Here's the tutorial i tried following, I am using angular 2 keep in mind that i'm implementing onto ionic not a webapp (https://berndsgn.ch/angular2-and-feathersjs/). I'll try and recreate the message this week.

**Comment by daffl** [comment]
Sounds good. Please open a new issue if you still get an error and can recreate it with a small breaking example.
