### ISSUE TITLE
Typescript definition bug

### ISSUE THREAD

**Issue by superbarne** [feathersjs/feathers-socketio#63]
### Steps to reproduce

it should be:
declare function socketio(connections:any, options?:any):**Function**;
right?
https://github.com/feathersjs/feathers-socketio/blob/master/client.d.ts#L3

### Expected behavior

Because it returns a Function:
https://github.com/superbarne/feathers-socketio/blob/master/src/client.js#L18

**Comment by daffl** [comment]
Sounds about right. If you submit a PR with the fix we can get a patch out right away.

**Comment by superbarne** [comment]
@daffl done

**Comment by daffl** [comment]
Closed via #64
