### ISSUE TITLE
Add headers and remote ip address to socket.feathers

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-socketio#67]
This is too common of a request to not be next on the list.  There are a lot of headers that match between the transports: https://gist.github.com/marshallswain/b775c7b6d7a9b2429b0eb6fe669a2bfd  

We don't currently expose these headers for sockets.

```js
app.configure(socketio(function (io) {
  io.on('connection', function (socket) {
    Object.assign(socket.feathers, {headers: socket.handshake.headers});
    socket.feathers.ip = socket.conn.remoteAddress;
  });
}));
```

**Comment by daffl** [comment]
See discussion in https://github.com/feathersjs/feathers-primus/issues/46#issuecomment-293024630
