### ISSUE TITLE
Connection closed before receiving a handshake response 

### ISSUE THREAD

**Issue by huytran0605** [feathersjs/feathers-socketio#84]
Currently, the code in server i use config like example.
```
app.configure(socketio(function(io) {
  io.on('connection', function(socket) {
    socket.emit('news', { text: 'A client connected!' });
    socket.on('my other event', function (data) {
      console.log(data);
    });
  });
}));
```
But code in client, i'm using like this:
```
import io from 'socket.io-client';

const socket = io('http://localhost:8080', { transports: ['websocket'], upgrade: false });
```

i got error like this on console
```
VM47643:161 WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=3&transport=websocket' failed: Connection closed before receiving a handshake response
```
i search anything relate `handshake response` but i still can not connect socket.
FYI, when i directly config socketio in `index.js`, i can connect.
```
import socketio from 'socket.io';
const server = app.listen(8080);
const io = socketio(server);
server.on('listening', () =>
    logger.info(`Feathers application started on ${app.get('host')}:${port}`),
  );
```

**Comment by daffl** [comment]
I would try with the default options like

```js
import io from 'socket.io-client';

const socket = io('http://localhost:8080');
```

And see if the same error happens. It also depends how the application is set up (did you configure `feathers-socketio` properly?).

**Comment by huytran0605** [comment]
Here is error when ai use default options:
```
GET http://localhost:8080/socket.io/?EIO=3&transport=polling&t=LtevyLS 404 (Not Found)
Request.create @ polling-xhr.js:264
Request @ polling-xhr.js:165

XMLHttpRequest cannot load http://localhost:8080/socket.io/?EIO=3&transport=polling&t=LtevyLS. The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:3000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

Default method will be long-polling and it like we call api not found 

```
404Route: /socket.io/?EIO=3&transport=polling&t=LtevyLS - Page not found
```

**Comment by daffl** [comment]
It must be something with your setup which is much easier to investigate with a repository to reproduce the issue.

**Comment by huytran0605** [comment]
Ok i will investigate more. For now, i'm using config socketIo in index.js like this
```
import socketio from 'socket.io';
const server = app.listen(8080);
const io = socketio(server);
server.on('listening', () =>
    logger.info(`Feathers application started on ${app.get('host')}:${port}`),
  );
```

**Comment by Zalasanjay** [comment]
i'm also facing problem like you @huytran0605 
getting this error : failed: Connection closed before receiving a handshake response

this is the code of my front-end in .vue file

`import io from 'socket.io-client';
  import feathers from 'feathers/client';
  import socketio from 'feathers-socketio/client';

  var socket = io('wss://ws.xxxxxxxx:4038', { transports: ['websocket']})
  var app = feathers();
  app.configure(socketio(socket));
  var message = app.service('vshopdata');
  Vue.use(feathers);`

this is the code of my back-end in app.js file

`const express = require('@feathersjs/express');
const feathers = require('@feathersjs/feathers');
const socketio = require('@feathersjs/socketio');

const app = express(feathers());
app.configure(configuration(path.join(__dirname, '..')))

app.configure(socketio(4038, {
  wsEngine: 'uws',
  origin: '*.xxxxxx.xx:*'
}));`

**Comment by ramsestom** [comment]
I think it is a related to a bug in the version of socket.io used by @feathersjs/socket.io that is solved with the latest version of socket.io (2.1.0): https://github.com/socketio/socket.io/issues/2294
Try to update to the latest version of socket.io to see if you still have this issue

**Comment by daffl** [comment]
I felt it might be something like that given the amount of issues around Socket.io and timeouts recently. I'll make a new patch release that will use that version.
